### ISSUE TITLE
`RawBytes::as_bytes` should be unsafe

### ISSUE THREAD

**Issue by stevenengler** [zxch3n/append-only-bytes#1]
The `RawBytes::as_bytes` allows reading from uninitialized memory. For example, the following is UB:

```rust
let bytes = RawBytes::with_capacity(10);
println!("{}", bytes.as_bytes());
```

I don't think you can invoke this through the public API because of the `len` field of `AppendOnlyBytes`, but `as_bytes` is still unsound.

An alternative would be to have `as_bytes()` return `&[MaybeUninit<u8>]` instead.

**Comment by zxch3n** [comment]
Thanks for reporting this! It's fixed now
